apiVersion: v1
kind: Pod
metadata:
  name: test-liveness-probe
spec:
  containers:
  - name: test
    image: jackson1202/test:1.0
    ports:
    - name: http
      containerPort: 8080
    startupProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 10
      failureThreshold: 12
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 5
      failureThreshold: 3